# frozen_string_literal: true

source 'https://rubygems.org'

gem 'debug', '~> 1.8'
gem 'minitest', '~> 5.19'
gem 'overcommit', '~> 0.60.0'
gem 'rake', '~> 13.0', '>= 13.0.6'
gem 'reek', '~> 6.1', '>= 6.1.4'
gem 'rspec-core', '~> 3.12', '>= 3.12.2'
gem 'rspec-expectations', '~> 3.12', '>= 3.12.3'
gem 'rspec-mocks', '~> 3.12', '>= 3.12.6'
gem 'rubocop', '~> 1.55', '>= 1.55.1'
gem 'rubocop-capybara', '~> 2.18'
gem 'rubocop-factory_bot', '~> 2.23', '>= 2.23.1'
gem 'rubocop-minitest', '~> 0.31.0'
gem 'rubocop-rake', '~> 0.6.0'
gem 'rubocop-rspec', '~> 2.23'
