source "https://rubygems.org"

gem 'rake', '~> 13.0', '>= 13.0.6'
gem 'reek', '~> 6.1', '>= 6.1.4'
gem 'rubocop', '~> 1.55', '>= 1.55.1'
gem 'rubocop-rake', '~> 0.6.0'
gem 'rspec-core', '~> 3.12', '>= 3.12.2'
gem 'rspec-expectations', '~> 3.12', '>= 3.12.3'
gem 'rspec-mocks', '~> 3.12', '>= 3.12.6'