# frozen_string_literal: true

source 'https://rubygems.org'

gem 'debug', '~> 1.8'
gem 'rake', '~> 13.0', '>= 13.0.6'
gem 'rake-compiler', '~> 1.2', '>= 1.2.5'
gem 'rspec-core', '~> 3.12', '>= 3.12.2'
gem 'rspec-expectations', '~> 3.12', '>= 3.12.3'
gem 'rspec-mocks', '~> 3.12', '>= 3.12.6'
