# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rake/testtask'
require "rake/extensiontask"
require 'rspec/core/rake_task'

task default: %i[spec]

Rake::ExtensionTask.new "my_malloc" do |ext|
  ext.lib_dir = "lib/my_malloc"
end

RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = FileList['spec/**/*_spec.rb']
end
